# Stage 1: Build
FROM node:20-alpine AS build

# Set the working directory for the build stage
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies (including devDependencies)
RUN yarn install

# Copy the rest of the application code
COPY . .

# Build the project
RUN yarn build

# Stage 2: Production
FROM node:20-alpine

# Set the working directory for the production stage
WORKDIR /app

# Copy only the package.json and yarn.lock from the build stage
COPY package.json yarn.lock ./

# Install only production dependencies
RUN yarn install --production

# Copy the built application from the build stage
COPY --from=build /app/dist /app/

# Expose the port your application runs on
EXPOSE 3000

# Define the command to run your application
CMD ["node", "server.js"]
